import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { ConfigProvider, App } from "antd";
import SysNavWrapper from "./components/SysNavWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#262626",
            },
          }}
        >
          <AntdRegistry>
            <App>
              <div className="sysRoot">
                <SysNavWrapper>
                  {children}
                </SysNavWrapper>
              </div>
            </App>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
